#define NEON_DECALS_PLANE -41	// Неоновые структурки

// Neon pallette
#define LIGHT_COLOR_HOTPINK			 "#F419A0"
#define LIGHT_COLOR_NEONGREEN		 "#1FFF0F"
#define LIGHT_COLOR_NEONRED   		 "#f80000"
#define LIGHT_COLOR_NEONYELLOW		 "#FFF01F"
#define LIGHT_COLOR_NEONLIGHTBLUE	 "#7df9ff"
#define LIGHT_COLOR_NEONBLUE		 "#4D4DFF"
#define LIGHT_COLOR_NEONDARKBLUE	 "#000370"
#define LIGHT_COLOR_NEONORANGE		 "#FF5733"

#define LIGHT_COLOR_RED        "#FA6496"
