DEFINE_BITFIELD(bodytype, list(
	"BODYTYPE_ORGANIC" = BODYTYPE_ORGANIC,
	"BODYTYPE_ROBOTIC" = BODYTYPE_ROBOTIC,
	"BODYTYPE_HUMANOID" = BODYTYPE_HUMANOID,
	"BODYTYPE_KEPORI" = BODYTYPE_KEPORI,
	"BODYTYPE_VOX" = BODYTYPE_VOX,
	"BODYTYPE_TAJARAN" = BODYTYPE_TAJARAN,
	))
